apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    name: 'in-cluster'
    namespace: prometheus
  source:
    chart: prometheus-community/kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 35.2.0
    helm:
      releaseName: prometheus
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
