apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
spec:
  project: default
  destination:
    namespace: helm-guestbook
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/bubnovd/Pres_GitOps_ArgoCD'
    path: argocd/manifests/helm-guestbook
    targetRevision: master
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=false
      - CreateNamespace=true
